#!/bin/bash

ELEV=90
AZIM=0
python -m src.draw_rendering_region \
    --dataset_dir_path /home/ubuntu/data/synthetic_scenes/train/shoe \
    --dataset_dir_name small_rgb \
    --output_path /home/ubuntu/data/synthetic_scenes/outputs/shoe/rendering_region/shoe.jpg \
    --pose_dir_name pose \
    --image_ext png \
    --width 256 \
    --height 256 \
    --t_n 0.0 \
    --t_f 2.5 \
    --elev ${ELEV} \
    --azim ${AZIM} \
    --camera_interval 1

